# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83227082f4bb97b0fdf9984d18781586967ffd238adc57e2b690a9946247dd2ae373592c863afd0a20eaa07eac3a05d5fd9402ef3fb7d1c2869c6a9c62b1b6cb

test:
  secret_key_base: 2a2b941aa4b8fa2c350039c54f63bc97fb8b2a356044bc90aef0bed20beff9f10735ad8a8588bba9dfbac5be224aecb1eed6e6c2f93db4364dc3af3c5ebee3c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
